development:
  adapter: postgresql
  encoding: unicode
  database: o_hi_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: o_hi_test
  pool: 5
  username: myapp
  password: password1
